### PR TITLE
New community ad: EFF

### PR DESCRIPTION
**Pull request by feross**
What do folks think of adding this as the first community ad? For: https://github.com/feross/funding/issues/14

```
                                                                                 
                           Electronic Frontier Foundation                        
                                                                                 
        Protect digital privacy and free expression. EFF's public interest       
        legal work, activism, and software development preserve fundamental      
                                      rights.                                    
                                                                                 
                    https://supporters.eff.org/donate/standardjs                 
                                                                                
```

### CODE REVIEW

**Comment by kemitchell** [comment]
Did EFF pay for it?

**Comment by feross** [comment]
No – the idea of #14 is to create some sponsor messages for community causes that we support. Non-profits, other OSS projects that have some message to get out, community conferences, etc.

**Comment by kemitchell** [comment]
Doesn't that dilute the point, and what advertisers should be willing to pay?

**Comment by osmarks** [comment]
Has the EFF been asked about this?

**Pull request closed without merging**
